### ISSUE TITLE
Error on my endpoint 

### ISSUE THREAD

**Issue by nonfungibletunji** [nerdsupremacist/Graphaello#26]
/Users/stunjiturner/Downloads/CodeReviewRepos/CRY/Graphaello.swift:895:14: Invalid redeclaration of 'Service'

` static var Service: FragmentPath<Crystallize.Service> { .init() }`

https://api.crystallize.com/sightuary/catalogue, public graphql endpoint

**Comment by nerdsupremacist** [comment]
Thank you for reporting this. This should be simple enough. I guess I never expected a name starting with an underscore and messed up the casing in there

**Comment by nerdsupremacist** [comment]
Alright! 
Fixed it with 0.1.0-beta.3. Please run:
```
brew upgrade graphaello
```
