### ISSUE TITLE
Graphaello Buildtime error: Keyword 'repeat' cannot be used as an identifier

### ISSUE THREAD

**Issue by satorusaka** [nerdsupremacist/Graphaello#37]
The API I'm using has "repeat" as a field, which is a swift reserved keyword.

Graphaello.swift:
``` swift
...
case repeat = "REPEAT"   // ".../AL/Graphaello.swift:4222:18: Keyword 'repeat' cannot be used as an identifier here"
...
```

Theres will always be a swift compiler error on Buildtime using that API.

A fix would be to use backticks to escape the keyword.

**Comment by nerdsupremacist** [comment]
Thanks for the heads up.
Soon the new release should be up: https://github.com/nerdsupremacist/Graphaello/actions/runs/1078551590

Please let mw know if it still doesn't work.
(PS: I accidentally closed the issue when I mentioned it in the commit message. I won't close it until I know that it works for sure)

**Comment by satorusaka** [comment]
The fix worked, thanks!
