### ISSUE TITLE
Generated view initializers don't camelize default values for enums

### ISSUE THREAD

**Issue by dewski** [nerdsupremacist/Graphaello#41]
My GraphQL API has an enum which is used as a default value in a field, and when my `Grapheaello.swift` is generated it does not camelize the enum (`API.Lang.enUs`) when building out the query renderer function parameters:

```swift
extension API {
  // lang should be:
  // lang: API.Lang? = API.Lang.enUs
  func contentView<Loading: View>(lang: API.Lang? = API.Lang.en_us,
                                  @ViewBuilder loading: () -> Loading) -> some View {
      return QueryRenderer(client: client,
                            query: ApolloAPIContentViewQuery(lang: lang),
                            loading: loading(),
                            error: { BasicErrorView(error: $0) }) { (data: ApolloAPI.ContentViewQuery.Data) -> ContentView in

          ContentView(data: data)
      }
  }
}
```

For my code to compile I have to modify the Swift to be:

```swift
extension API {
  func contentView<Loading: View>(lang: API.Lang? = API.Lang.enUs,
                                  @ViewBuilder loading: () -> Loading) -> some View {
      return QueryRenderer(client: client,
                            query: ApolloAPIContentViewQuery(lang: lang),
                            loading: loading(),
                            error: { BasicErrorView(error: $0) }) { (data: ApolloAPI.ContentViewQuery.Data) -> ContentView in

          ContentView(data: data)
      }
  }
}
```

Here is the enum that is generated from the GraphQL schema:

```graphql
# Lang
enum Lang {
  # en-GB
  EN_GB

  # en-US
  EN_US
}
```

```swift
public enum ApolloAPI {
  /// Lang
  public enum Lang: RawRepresentable, Equatable, Hashable, CaseIterable, Apollo.JSONDecodable, Apollo.JSONEncodable {
    public typealias RawValue = String
    /// en-US
    case enUs
    /// en-GB
    case enGb
    /// Auto generated constant for unknown enum values
    case __unknown(RawValue)

    public init?(rawValue: RawValue) {
      switch rawValue {
        case "EN_US": self = .enUs
        case "EN_GB": self = .enGb
        default: self = .__unknown(rawValue)
      }
    }

    public var rawValue: RawValue {
      switch self {
        case .enUs: return "EN_US"
        case .enGb: return "EN_GB"
        case .__unknown(let value): return value
      }
    }

    public static func == (lhs: Lang, rhs: Lang) -> Bool {
      switch (lhs, rhs) {
        case (.enUs, .enUs): return true
        case (.enGb, .enGb): return true
        case (.__unknown(let lhsValue), .__unknown(let rhsValue)): return lhsValue == rhsValue
        default: return false
      }
    }

    public static var allCases: [Lang] {
      return [
        .enUs,
        .enGb,
      ]
    }
  }
}
```

I did some debugging and found that the expression passed to `QueryRendererArgument` isn't camelizing the enum properly when rendering the [Struct<Prepared>.swift.stencil](https://github.com/nerdsupremacist/Graphaello/blob/develop/templates/swift/Struct%3CPrepared%3E.swift.stencil):

```
Graphaello.QueryRendererArgument(name: "lang", type: "API.Lang?", expression: Optional(SwiftSyntax.ExprSyntax))
```

I'm not exactly sure how to change what is returned from `SwiftSyntax.ExprSyntax` otherwise I'd submit a PR. Any help is appreciated!

**Comment by nerdsupremacist** [comment]
Hi! Sorry for the late reply.

Given the fact that it wrote `API.Lang.en_us` my guess is that it's the default value for the field, and Graphaello transpiled GraphQL to Swift wrong. The code to deal with converting a GraphQL Enum Value to Swift is [here](https://github.com/nerdsupremacist/Graphaello/blob/539d473e7b59f18f51f7d8dc40f84ebe9e6087e8/Sources/Graphaello/Processing/Pipeline/Component/Transpilation/BasicGraphQLToSwiftTranspiler.swift#L52).

That code is already taking care of converting it to camel case, but apparently it's doing it wrong. Here we're running into trouble for cases where Apollo and Graphaello use different strategies for camel casing. I'll send a fix soon.

**Comment by nerdsupremacist** [comment]
Can confirm that it should now be fixed. Tested your case in a playground.

<img width="894" alt="Screen Shot 2021-12-19 at 9 39 58 PM" src="https://user-images.githubusercontent.com/13184158/146691759-3d21e051-f1e7-4092-be24-a58f58e41163.png">

 0.1.0-beta.9 should be making it's way to the brew formula in a few mins. Run `brew upgrade graphaello`
