### ISSUE TITLE
Xcode 11.4 will not build.

### ISSUE THREAD

**Issue by stunjiturner** [nerdsupremacist/Graphaello#6]
SwiftSyntax parser library isn't compatible
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by stunjiturner** [comment]
/Applications/Xcode.app/Contents/Developer
yes brand new install

**Comment by nerdsupremacist** [comment]
Ok. I was able to reproduce the issue. 

Thanks I'll come up with a fix soon

**Comment by nerdsupremacist** [comment]
Alright. I did some digging...

Looks like the version of SwiftSyntax needs to match the version of `libSwiftSyntax.dylib` perfectly. 

So I'll update the version of it to use Swift 5.2... and force Xcode 11.4 in the brew formula

It's a good thing that this came up while it's still in Alpha. We will need to come up with a way to make sure the versions match during install. 

It's fuzzy wether or not we're allowed to just ship Graphaello with `libSwiftSyntax.dylib` in the repo directly. 
I assume that would be a License or Terms and Conditions infringement

**Comment by nerdsupremacist** [comment]
@stunjiturner I have a fix, but apple hasn't released SwiftSyntax for 5.2 yet. They just have a branch for it. 
So I'm not comfortable replacing the current version with that, yet.

I have a branch for it too.
If you want to use it you can:

First make sure you uninstall Graphaello first
```
brew uninstall graphaello
```

Then you clone it and install from source:
```
git clone https://github.com/nerdsupremacist/Graphaello.git
cd graphaello
git checkout swift-5.2-branch
sudo make install
```

I hope this helps! 🙃

**Comment by stunjiturner** [comment]
Do I need to do a graphaello command line codegen at the countries example repo, because is still get build errors, after rebuilding graphaello with the swift branch 5.2

**Comment by nerdsupremacist** [comment]
My bad. Didn't actually test it on the project... I just checked if codegen went through...

I believe I fixed it. But SwiftSyntax got a lot of Breaking Changes. 
And I'm not sure if this branch is 100% ready... But you're welcome to try it.

To update go to your cloned source of Graphaello and run:
```
sudo make uninstall
git pull
sudo make install
```

**Comment by nerdsupremacist** [comment]
@stunjiturner I released the version with the changes. If you want to you can install the version from brew again

**Comment by stunjiturner** [comment]
Great , because the local version is running great. I will try code generation with the Apollo-IOS sample tutorial, because I never got it working.
What are the steps/order for using a external graphql api and graphaello cli

Step 1. graphaello init
Step 2.  graphaello add “external graphql api”
Step 3. graphaello codegen
